final_web
Many98/real_estate pull request #22
Opened 2022-12-10 17:49 UTC by nguyet62

2022-12-11 11:30 UTC, Daniel-Karlik commented on src/web.py
> +    mapping = {'has_balcony': 'Má balkón', 'has_cellar': 'Má sklep', 'has_garage': 'Má garaz', 'has_lift': 'Má výtah',
'has_garage': 'Má garáž'

2022-12-11 11:33 UTC, Daniel-Karlik commented on src/web.py
> +               'energy_effeciency': 'Energetická efecience',
Je možno nechat, nebo nahradit 'Energetická náročnost'?

2022-12-11 11:35 UTC, Daniel-Karlik commented on src/web.py
> +                    help='Zadejte dispozici bytu. Zadaním dispozice docílíte zpřesnění predikce.')
Zadáním dispozice

2022-12-11 11:36 UTC, Daniel-Karlik commented on src/web.py
> +        help='Zadejte energetickou efecienci bytu. Zadáním tohoto atributu docílíte zpřesnění predikce.')
Pokud nahradíme, pak 'energetickou náročnost'

2022-12-11 11:37 UTC, Daniel-Karlik commented on src/web.py
> +                         help='Zadejte typ vlastnictví. Zadanim tohoto atributu docilite spresneni predikce.')
Zadejte typ vlastnictví. Zadáním tohoto atributu docílíte zpřesnění predikce.

2022-12-11 11:38 UTC, Daniel-Karlik commented on src/web.py
> +                         help='Zadejte miru vybavenosti bytu. Zadáním tohoto atributu docílíte zpřesnění predikce.')
Zadejte míru...

2022-12-11 11:43 UTC, Daniel-Karlik requested changes
Přidal jsem tam pár komentářů k textíkům, které by mohli být ještě doupraveny.

2022-12-11 12:35 UTC, Many98 commented
Super, diky za uzitocny review

2022-12-12 00:09 UTC, Daniel-Karlik approved these changes

2022-12-12 10:03 UTC, Many98 approved these changes
Added new fixes, now it seems to be ok.

2022-12-12 10:03 UTC, merged